export const foodCategories = [
  { id: 1, name: "피자", image: "/assets/pizza.svg" },
  { id: 2, name: "샐러드", image: "/assets/salad.svg" },
  { id: 3, name: "햄버거", image: "/assets/hamburger.svg" },
  { id: 4, name: "한식", image: "/assets/koreanfood.svg" },
  { id: 5, name: "분식", image: "/assets/snackfood.svg" },
  { id: 6, name: "치킨", image: "/assets/chicken.svg" },
  { id: 7, name: "초밥", image: "/assets/sushi.svg" },
  { id: 8, name: "샌드위치", image: "/assets/sandwhich.svg" },
  { id: 9, name: "파스타", image: "/assets/pasta.svg" },
  { id: 10, name: "디저트", image: "/assets/dessert.svg" },
  { id: 11, name: "커피", image: "/assets/coffee.svg" },
  { id: 12, name: "더보기", image: "/assets/plusinfo.svg" },
];

export const storeList = [
  {
    rank: 1,
    name: "샐로리 한남점",
    rating: 4.9,
    reviews: 3919,
    deliveryTime: "15~25분",
    deliveryFee: 2000,
    minOrder: 13000,
    purMethod: "토스결제만 현장결제 안됨",
  },
  {
    rank: 2,
    name: "샐로리 한남점",
    rating: 4.9,
    reviews: 3919,
    deliveryTime: "15~25분",
    deliveryFee: 2000,
    minOrder: 13000,
    purMethod: "토스결제만 현장결제 안됨",
  },
  {
    rank: 3,
    name: "샐로리 한남점",
    rating: 4.9,
    reviews: 3919,
    deliveryTime: "15~25분",
    deliveryFee: 2000,
    minOrder: 13000,
    purMethod: "토스결제만 현장결제 안됨",
  },
  {
    rank: 4,
    name: "샐로리 한남점",
    rating: 4.9,
    reviews: 3919,
    deliveryTime: "15~25분",
    deliveryFee: 2000,
    minOrder: 13000,
    purMethod: "토스결제만 현장결제 안됨",
  },
  {
    rank: 5,
    name: "샐로리 한남점",
    rating: 4.9,
    reviews: 3919,
    deliveryTime: "15~25분",
    deliveryFee: 2000,
    minOrder: 13000,
    purMethod: "토스결제만 현장결제 안됨",
  },
];

export const saladMenu = [
  {
    name: "토마토 샐러드",
    isBest: true,
    price: 7600,
    ingredients: "계란, 옥수수, 양파, 올리브, 베이컨, \n" + "시저드레싱",
  },
  {
    name: "토마토 샐러드",
    isBest: false,
    price: 7600,
    ingredients: "계란, 옥수수, 양파, 올리브, 베이컨, \n" + "시저드레싱",
  },
  {
    name: "토마토 샐러드",
    isBest: false,
    price: 7600,
    ingredients: "계란, 옥수수, 양파, 올리브, 베이컨, \n" + "시저드레싱",
  },
  {
    name: "토마토 샐러드",
    isBest: false,
    price: 7600,
    ingredients: "계란, 옥수수, 양파, 올리브, 베이컨, \n" + "시저드레싱",
  },
];
