const marketcategories = [
  {
    name: "샐러리 한남점",
    rank: 1,
    rating: 4.9,
    reviewCount: 3919,
    deliveryTime: "13분~30분",
    deliveryFee: "2,000원",
    path: "/store/1",
  },
  {
    name: "옐로우푸드 샐러드",
    rank: 2,
    rating: 4.8,
    reviewCount: 1129,
    deliveryTime: "13분~30분",
    deliveryFee: "2,000원",
    path: "/store/2",
  },
  {
    name: "씬더볼드 한남점",
    rank: 3,
    rating: 4.8,
    reviewCount: 919,
    deliveryTime: "13분~30분",
    deliveryFee: "2,000원",
    path: "/store/3",
  },
  {
    name: "THE 샐러드가득담은",
    rating: 5.0,
    reviewCount: 27,
    deliveryTime: "13분~30분",
    deliveryFee: "2,000원",
    path: "/store/4",
  },
  {
    name: "파스토보이",
    rating: 4.8,
    reviewCount: 801,
    deliveryTime: "13분~30분",
    deliveryFee: "2,000원",
    path: "/store/5",
  },
  {
    name: "힘난다 샐러드",
    rating: 4.9,
    reviewCount: 3919,
    deliveryTime: "13분~30분",
    deliveryFee: "2,000원",
    path: "/store/6",
  },
];

export default marketcategories;
